### ISSUE TITLE
Error after running your project

### ISSUE THREAD

**Issue by Sancetiano** [Pawan243/Django-Gym-Management#2]
I am getting a template syntax error like shown in the screenshot below.  Could you fix it?

![Screenshot 2023-04-16 233828](https://user-images.githubusercontent.com/114907982/232332903-27168ad6-60de-4921-8be7-1b6a983bedce.png)

**Comment by Pawan243** [comment]
Hey,

I can help you on this.

Please make space between "if" and "equal".

You have written "if" block like {% ifequal ....}

But instead it should be like this {% if equal....}

Please try this. Hope it will help you.
